get_planning_scene_server:
  ros__parameters:

    # Topic and frame settings
    point_cloud_topic: "/camera_head/depth/color/points"
    rgb_image_topic: "/camera_head/color/image_raw"
    target_frame: "base_link"

    # Cropping settings
    enable_cropping: true
    crop_min_x: 0.10
    crop_max_x: 1.1
    crop_min_y: 0.00
    crop_max_y: 0.90
    crop_min_z: -inf
    crop_max_z: inf

    # Plane and object segmentation parameters
    max_iterations: 100
    distance_threshold: 0.01
    z_tolerance: 0.03
    angle_tolerance: 0.9990482216
    plane_segmentation_threshold: 0.001
    min_cluster_size: 150
    max_cluster_size: 1000000
    cluster_tolerance: 0.02
    normal_estimation_k: 30
    w_inliers: 1.0
    w_size: 1.0
    w_distance: 1.0
    w_orientation: 1.0
    max_plane_segmentation_iterations: 1000
    plane_segmentation_distance_threshold: 0.01

    # Support surface parameters
    support_surface_name: "support_surface"
    min_surface_thickness: 0.0001

    # Normal, curvature, and RSD estimation parameters
    k_neighbors: 30
    max_plane_error: 0.01
    max_iterations_normals: 100
    min_boundary_neighbors: 10
    rsd_radius: 0.02

    # Cluster extraction parameters
    nearest_neighbors: 30
    smoothness_threshold: 20.0
    curvature_threshold: 0.2

    # Object segmentation parameters
    num_iterations: 5
    inlier_threshold: 85
    hough_radius_bins: 50
    hough_center_bins: 50
    ransac_distance_threshold: 0.001
    ransac_max_iterations: 1000

    # ✅ Tweaked Circle inlier filtering parameters
    circle_min_cluster_size: 15
    circle_max_clusters: 3
    circle_height_tolerance: 0.05                # Increased for taller object
    circle_curvature_threshold: 0.003            # Loosened to accept lower curvature
    circle_radius_tolerance: 0.025               # Matches your cylinder radius (0.03)
    circle_normal_angle_threshold: 0.35          # More angle deviation accepted
    circle_cluster_tolerance: 0.03               # Slightly looser cluster tolerance

    # 🔻 Suppress Line Detection
    line_min_cluster_size: 30
    line_max_clusters: 0                         # Disable line detection completely
    line_curvature_threshold: 0.0008             # Stricter so fewer line candidates
    line_cluster_tolerance: 0.025
    line_rho_threshold: 0.005
    line_theta_threshold: 0.05

    # Shape fitting parameters
    shape_fitting_max_iterations: 1000
    shape_fitting_distance_threshold: 0.015      # Slightly looser
    shape_fitting_min_radius: 0.02               # Cylinder radius = 0.03
    shape_fitting_max_radius: 0.05
    shape_fitting_normal_distance_weight: 0.05   # Lower weight on normal
    shape_fitting_normal_search_radius: 0.05

    # Debug output settings
    output_directory: "/home/darsh/Downloads/"
    debug_pcd_filename: "debug_cloud.pcd"
