# Default initial positions for ur's ros2_control fake system

initial_positions:
  elbow_joint: -0.3298
  finger_joint: 0.0
  shoulder_lift_joint: 4.8946
  shoulder_pan_joint: 0.0
  wrist_1_joint: 4.6169
  wrist_2_joint: 0.0041
  wrist_3_joint: 1.6489
