# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    grip_action_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains: 
      shoulder_pan_joint: {p: 1000.0, i: 0.0, d: 0.1}
      shoulder_lift_joint: {p: 1000.0, i: 0.0, d: 0.1}
      elbow_joint: {p: 1000.0, i: 0.0, d: 0.1}
      wrist_1_joint: {p: 1000.0, i: 0.0, d: 0.1}
      wrist_2_joint: {p: 1000.0, i: 0.0, d: 0.1}
      wrist_3_joint: {p: 1000.0, i: 0.0, d: 0.1}
    allow_nonzero_velocity_at_trajectory_end: true

grip_action_controller:
  ros__parameters:
    joints:
      - finger_joint
