# Depth image
- ros_topic_name: "camera_head/depth/image_raw"
  gz_topic_name: "camera_head/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: false

# Color image
- ros_topic_name: "camera_head/color/image_raw"
  gz_topic_name: "camera_head/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: false

# Camera info
- ros_topic_name: "camera_head/depth/camera_info"
  gz_topic_name: "camera_head/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: false

# Point cloud
- ros_topic_name: "camera_head/depth/color/points"
  gz_topic_name: "/world/default/model/ur/link/base_link/sensor/camera_head/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
  lazy: false

